---
minimum_pre_commit_version: 1.17.0
exclude: '.idea|.vscode'
repos:
    ####### Run `commitlint` based on conventional commits
    - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
      rev: v2.2.1
      hooks:
          - id: commitlint
            stages: [commit-msg]
            additional_dependencies:
                - conventional-changelog-conventionalcommits
    ####### Initial Error checking
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v2.4.0
      hooks:
          - id: no-commit-to-branch
            args: [--branch, master]
          - id: trailing-whitespace
          - id: end-of-file-fixer
            stages: [manual, commit, push]
          - id: check-merge-conflict
    ####### Code Formatters
    - repo: https://github.com/prettier/prettier
      rev: 1.19.1
      hooks:
          - id: prettier
            stages: [manual, commit, push]
            types: [yaml]
    - repo: https://github.com/psf/black
      rev: 19.10b0
      hooks:
          - id: black
            language_version: python3.7
            types: [python]
    - repo: https://github.com/pre-commit/mirrors-pylint
      rev: v2.3.1
      hooks:
          - id: pylint
            types: [python]
    ####### final hooks
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v2.4.0
      hooks:
          - id: check-ast
          - id: debug-statements
          - id: flake8
####### Meta hooks, useful for debugging
#    - repo: meta
#      hooks:
#          - id: check-hooks-apply
#          - id: check-useless-excludes
#          - id: identity
#            types: [file]
