[tox]
isolated_build = true
envlist = py37

[testenv]
whitelist_externals = poetry
commands =
    poetry install -v
    poetry run pytest tests/


# .coveragerc to control coverage.py
[coverage:run]
branch = True
source = oxide
omit = .venv

[coverage:report]
# Regexes for lines to exclude from consideration
exclude_lines =
    # Don't complain if tests don't hit defensive assertion code:
    raise AssertionError
    raise NotImplementedError

    # Don't complain if non-runnable code isn't run:
    if 0:
    if __name__ == .__main__.:

ignore_errors = True


[pytest]
minversion = 3.0
norecursedirs = .venv
addopts =  -ra  --color=yes  --cov-append --cov-report=
