"""Force name to create a new flower

Revision ID: 96d99331a993
Revises:
Create Date: 2020-04-05 16:56:43.412030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "96d99331a993"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "flower",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("latin_name", sa.String(length=120), nullable=True),
        sa.Column("genus", sa.String(length=128), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_flower_latin_name"), "flower", ["latin_name"], unique=True)
    op.create_index(op.f("ix_flower_name"), "flower", ["name"], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_flower_name"), table_name="flower")
    op.drop_index(op.f("ix_flower_latin_name"), table_name="flower")
    op.drop_table("flower")
    # ### end Alembic commands ###
